---
- name: Install apache2
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apache2
    - openssl

# - name: Copy apache2 config files.
#   copy:
#     src: " {{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: root
#     group: root
#     mode: 0644
#   with_items:
#     - src: "httpd.conf"
#       dest: "/etc/apache2/conf/httpd.conf"
#     - src: "httpd-vhosts.conf"
#       dest: "/etc/httpd/conf/httpd-vhosts.conf"
#
#   - name: Make sure Apache is started now and at boot.
#     service:
#       name: apache2
#       state: started
#       enabled: yes
