---
- hosts: all
  become: yes
  gather_facts: false

  roles:
    - role: common

    - role: apache

    - role: mysql-server

    - role: php

    - role: phpmyadmin

  tasks:
    - name:
      include_tasks: test_handler.yml
